[versions]
androidx-core = "1.9.0"

appcompat = "1.6.0"
material = "1.7.0"

compose-compiler = "1.3.2"
compose-bom = "2022.12.00"
compose-activity = "1.5.1"
compose-lifecycle = "2.5.1"
compose-navigation = "2.5.3"

hilt = "2.44"
hilt-navigation = "1.0.0"

coroutines = "1.3.9"

room = "2.5.0"

moshi = "1.14.0"

junit = "4.13.2"
junit-ext = "1.1.5"
espresso = "3.5.1"

compileSdk = "33"
minSdk = "26"
versionCode = "1"
versionName = "1.0"
jvmTarget = "1.8"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-debug-preview = { module = "androidx.compose.ui:ui-tooling" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-coroutines = { module = "androidx.room:room-ktx", version.ref = "room" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
core = ["androidx-core"]
ui-core = ["appcompat", "material"]
tests = ["junit"]
androidTests = ["junit-ext", "espresso"]
compose = ["compose-material", "compose-preview", "compose-activity", "compose-viewModel", "compose-navigation"]
compose-debug = ["compose-debug-preview"]
hilt = ["hilt", "hilt-navigation"]
room = ["room-runtime", "room-coroutines"]

[plugins]