#Additional rules defined in twitter-compose.yml will handle Compose checks

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'

style:
  active: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'